[package]
name = "atrinik-editor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
atrinik-editor-commands.workspace = true
atrinik-editor-document.workspace = true
atrinik-editor-preview.workspace = true
atrinik-editor-project.workspace = true
atrinik-editor-ui.workspace = true
sdl3.workspace = true

[lints]
workspace = true
